version: '3.8'
services:
  www:
    build: php
    working_dir: /var/www/html
    container_name: www
    extra_hosts:
      - dev.kafka.loc:127.0.0.1
      - host.docker.internal:host-gateway
    hostname: dev.kafka.loc
    ports:
      - "8888:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./project:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    restart: always
    networks:
      - kafka

volumes:
  db-data:
networks:
  kafka: