enqueue:
  default:
    transport:
      dsn: "rdkafka://"
      global:
        ### Make sure this is unique for each application / consumer group and does not change
        ### Otherwise, Kafka won't be able to track your last offset and will always start according to
        ### `auto.offset.reset` setting.
        ### See Kafka documentation regarding `group.id` property if you want to know more
        group.id: 'foo-app'
        metadata.broker.list: 'broker:9092'
      topic:
        auto.offset.reset: beginning
      ### Commit async is true by default since version 0.9.9.
      ### It is suggested to set it to true in earlier versions since otherwise consumers become extremely slow,
      ### waiting for offset to be stored on Kafka before continuing.
      commit_async: true
    client: ~